// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fabric_service.proto

package org.kong.proto;

public interface DownloadReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.DownloadReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string username = 1;</code>
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 1;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();
}
