// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fabric_service.proto

package org.kong.proto;

public interface DownloadRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.DownloadResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string card = 1;</code>
   */
  java.lang.String getCard();
  /**
   * <code>string card = 1;</code>
   */
  com.google.protobuf.ByteString
      getCardBytes();
}
