// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fabric_service.proto

package org.kong.proto;

public interface LoginReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.LoginReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 userid = 1;</code>
   */
  long getUserid();

  /**
   * <code>string username = 2;</code>
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 2;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>string userhash = 3;</code>
   */
  java.lang.String getUserhash();
  /**
   * <code>string userhash = 3;</code>
   */
  com.google.protobuf.ByteString
      getUserhashBytes();
}
