// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fabric_service.proto

package org.kong.proto;

public interface LoginRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.LoginResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 code = 1;</code>
   */
  long getCode();
}
