// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fabric_service.proto

package org.kong.proto;

public interface RegisterRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.RegisterResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 code = 1;</code>
   */
  long getCode();
}
