// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: register.proto

package org.kong.proto;

public interface RegisterReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.RegisterReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string username = 1;</code>
   */
  String getUsername();
  /**
   * <code>string username = 1;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();
}
